diffuse_trans: True
diffuse_rot: True

# R(3) diffuser arguments
r3:
  min_b: 0.1
  max_b: 20.0
  coordinate_scaling: 0.1

# SO(3) diffuser arguments
so3:
  num_omega: 1000
  num_sigma: 1000
  min_sigma: 0.1
  max_sigma: 1.5
  schedule: logarithmic
  cache_dir: .cache/
  use_cached_score: False
